_G.FishItConfig = _G.FishItConfig or {
    ["Fishing"] = {
        ["Auto Perfect"] = false,
        ["Random Result"] = false,

        ["Auto Favorite"] = true,
        ["Auto Unfavorite"] = false,
        ["Fish Name"] = {
            "Sacred Guardian Squid",
            {Name = "Ruby", Variant = "Gemstone"},
            {Tier = "Mythic", Variant = "Stone"},
            {Tier = "Mythic", Variant = "Gold"},
            {Tier = "Mythic", Variant = "Ghost"},
            {Tier = "Mythic", Variant = "Radioactive"},
            {Tier = "Mythic", Variant = "Lightning"},
            {Tier = "Mythic", Variant = "Midnight"},
            {Tier = "Mythic", Variant = "Fairy Dust"},
            {Tier = "Mythic", Variant = "Gemstone"},
            {Tier = "Mythic", Variant = "Corrupt"},
            {Tier = "Mythic", Variant = "Frozen"},
            {Tier = "Mythic", Variant = "Galaxy"},
            {Tier = "Mythic", Variant = "Holographic"},
            {Tier = "Mythic", Variant = "Leviathan Rage"},
            },

        ["Auto Accept Trade"] = true,
        ["Auto Friend Request"] = true,
    },
    ["Auto Trade"] = {
        ["Enabled"] = true,
        ["Whitelist Username"] = {"DilInvent"},
        ["Category Fish"] = {
            "Secret",
            {Tier = "Mythic", Variant = "Stone"},
            {Tier = "Mythic", Variant = "Gold"},
            {Tier = "Mythic", Variant = "Ghost"},
            {Tier = "Mythic", Variant = "Radioactive"},
            {Tier = "Mythic", Variant = "Lightning"},
            {Tier = "Mythic", Variant = "Midnight"},
            {Tier = "Mythic", Variant = "Fairy Dust"},
            {Tier = "Mythic", Variant = "Gemstone"},
            {Tier = "Mythic", Variant = "Corrupt"},
            {Tier = "Mythic", Variant = "Frozen"},
            {Tier = "Mythic", Variant = "Galaxy"},
            {Tier = "Mythic", Variant = "Holographic"},
            {Tier = "Mythic", Variant = "Leviathan Rage"},
        },
        ["Fish Name"] = {
            "Sacred Guardian Squid",
            {Name = "Ruby", Variant = "Gemstone"},
            -- {Variant = "Leviathan Rage"}, -- Variant Only
        },
        ["Item Name"] = {
            "Evolved Enchant Stone",
        },
    },
    ["Farm Coin Only"] = {
        ["Enabled"] = false, -- Farm coins only [ cant buy rod, bait, enchant, weather ]
        ["Target"] = 190000,
    },
    ["Selling"] = {
        ["Auto Sell"] = true,
        ["Auto Sell Threshold"] = "Mythic",
        ["Auto Sell Every"] = 100,
    },
    ["Doing Quest"] = {
        ["Auto Ghostfinn Rod"] = true,
        ["Auto Element Rod"] = false,
        ["Auto Diamond Rod"] = false,
        ["Unlock Ancient Ruin"] = true,
        ["Allowed Sacrifice"] = {
            "Ghost Shark",
            "Cryoshade Glider",
            "Panther Eel",
            "Queen Crab",
            "King Crab",
            "Giant Squid",
            "Blob Shark",
            "Ghost Shark",
            "Elshark Gran Maja",
            "Bone Whale",
            "Gladiator Shark",
            "King Jelly",
            "Mosasaur Shark",
        },
        ["FARM_LOC_SECRET_SACRIFICE"] = "Treasure Room",

        ["Minimum Rod"] = "Astral Rod",
    },
    ["WebHook"] = {
        ["Link Webhook"] = "https://discord.com/api/webhooks/996054378861559899/_ZKaOOdIxArjew6ZsXS6h9QjLHvXer5_xUzyZTWqO2OF2yyodVSQ-_bD8jK_gCH8IyS5",
        ["Auto Sending"] = true,
        ["Category"] = {"Secret"},

        ["Link Webhook Quest Complete"] = "https://discord.com/api/webhooks/1025982687619584150/2h_1Q-Ut2L9RGlu9oDFwYbXigizoeXEPnzy0M4IUCkIESlLp3Nla-4z-aZpxju3MyGkz",
    },
    ["Weather"] = {
        ["Auto Buying"] = true,
        ["Minimum Rod"] = "Astral Rod",
        ["Weather List"] = {
            "Wind",
            "Cloudy",
            "Storm",
        },
    },
    ["Potions"] = {
        ["Auto Use"] = true,
        ["Minimum Rod"] = "Astral Rod",
    },
    ["Totems"] = {
        ["Auto Use"] = true,
        ["Minimum Rod"] = "Ghostfinn Rod",
        ["Buy List"] = {
            ["Luck Totem"] = 24,
            "Luck Totem",
        },
    },
    ["Event"] = {
        ["Start Farm"] = true,
        ["Minimum Rod"] = "Ghostfinn Rod",
        ["Event List"] = {
            "Ghost Shark Hunt",
            "Shark Hunt",
            ["Ancient Lochness Monster"] = true,
        },
    },
    ["Enchant"] = {
        ["Auto Enchant"] = true,
        ["Roll Enchant"] = false,
        ["Evolved Roll Enchant"] = true,
        ["Enchant List"] = {
            "SECRET Hunter",
            "Mutation Hunter III",
            "Mutation Hunter II",
            "Cursed I",
        },
        ["Second Enchant"] = true,
        ["Allowed Sacrifice"] = {
            "Frostborn Shark",
            "Cryoshade Glider",
            "Gladiator Shark",
            "King Crab",
            "Queen Crab",
            "Blob Shark",
            "Skeleton Narhwal",
        },
        ["Second Enchant List"] = {
            "Cursed I",
            "Perfection",
            "Mutation Hunter II",
        },
        ["Minimum Rod"] = "Element Rod",
    },
    ["Bait List"] = {
        ["Auto Buying"] = true,
        ["Buy List"] = {
            "Midnight Bait",
            "Corrupt Bait",
            "Singularity Bait",
        },
        ["Endgame"] = "",
    },
    ["Rod List"] = {
        ["Auto Buying"] = true,
        ["Buy List"] = {
            "Luck Rod",
            "Grass Rod",
            "Midnight Rod",
            "Astral Rod",
            "Ares Rod",
            "Angler Rod",
        },
        ["Location Rods"] = {
            ["Fisherman Island"] = {"Starter Rod"},
            ["Kohana Volcano"] = {"Grass Rod"},
            ["Tropical Grove"] = {"Midnight Rod"},
            ["Ancient Ruin"] = {"Element Rod", "Ghostfinn Rod", "Angler Rod", "Ares Rod"},
        },
        ["Endgame"] = "",
    },

    ["ExtremeFpsBoost"] = true,
    ["UltimatePerformance"] = false,
    ["Disable3DRender"] = true,
    ["AutoRemovePlayer"] = true,

    ["AutoReconnect"] = true,
    ["HideGUI"] = true,
    ["EXIT_MAP_IF_DISCONNECT"] = true,
}
